# If this is true you get Debug Logs in your console, this may be a big spammy
DebugMode: true

NodeSettings:

  # Time in minutes nodes should reset
  ResetTimer: 5

WorldSettings:

  UseWorld: "Rust"

  StoneMaterial: DRIPSTONE_BLOCK
  MetalMaterial: DEEPSLATE_IRON_ORE
  SulfurMaterial: DEEPSLATE_GOLD_ORE

  MaxStoneNodes: 500
  MaxMetalNodes: 180
  MaxSulfurNodes: 150

  MaxNodeGenerationX: 767
  #767
  MaxNodeGenerationZ: 767
  #767

  DenyBlocksUnderNode:
    - "WATER"


  DenyStoneBiomeNodeSpawn:
    - "BEACH"
  DenyMetalBiomeNodeSpawn:
    - "BEACH"
  DenySulfurBiomeNodeSpawn:
    - "BEACH"
    - "PLAINS"

  InteractableBlocks:
    - "DRIPSTONE_BLOCK"
    - "DEEPSLATE_GOLD_ORE"
    - "DEEPSLATE_IRON_ORE"
  BreakableBlocks:
    - "DRIPSTONE_BLOCK"
    - "DEEPSLATE_GOLD_ORE"
    - "DEEPSLATE_IRON_ORE"
Items:

  Sulfur:
    Ore:
      CustomModelData: 77321 # Dont change this dude
      Material: RAW_GOLD
      Name: "&e&l&oUncooked Sulfur"
      Lore:
        - "&f "
        - "&e&oPut this into a furnace to refine it to"
        - "&e&l&oCooked Sulfur&7&o useful for bullets and explosives!"
    Cooked:
      CustomModelData: 77322 #Dont change this dude
      Material: GOLD_INGOT
  Stone:
    Ore:
      CustomModelData: 77323 # Dont change this dude
      RawCopper: "RAW_COPPER"
  Rock:
    HarvestAmount: 2